apiVersion: v1 
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: LoadBalancer
  ports:
  - name: goserver-service
    port: 80 #port service
    targetPort: 8000 #port container
    protocol: TCP